### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by AlexNek** [f2calv/yamlizr#177]
**Key**
- Share your full command line to execute the tool *taking care to redact anything private*!
-yamlizr.exe generate -pat aassddfffffgare53y6fceb7557azkhwtnqim33ergt  -org https://dev.azure.com/org1 -proj myproject -out c:/Test/_Devops
- Confirm which version of the tool you are using.
Can not find actual version number. Downloaded 22.12.2022

**Describe the bug**
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓   at CasCap.Utilities.YamlPipelineGenerator.GenBuildStage() in /_/src/CasCap.Apis.AzureDevOps/Utilities/YamlPipelineGenerator.cs:line 112               at CasCap.Utilities.YamlPipelineGenerator.GenPipeline() in /_/src/CasCap.Apis.AzureDevOps/Utilities/YamlPipelineGenerator.cs:line 67                  at CasCap.Commands.GenerateCommand.<>c__DisplayClass31_4.<OnExecuteAsync>g__ProcessDefinition|16(BuildDefinition buildDefinition) in /_/src/CasCap.DevOpsYamlizrCli/Commands/GenerateCommand.cs:line 241                                                                                                    at CasCap.Commands.GenerateCommand.OnExecuteAsync() in /_/src/CasCap.DevOpsYamlizrCli/Commands/GenerateCommand.cs:line 223                            at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)       at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)                                                                                                                                                       at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()                         --- End of stack trace from previous location ---                                                                                                        at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)                       at CasCap.Program.Main(String[] args) in /_/src/CasCap.DevOpsYamlizrCli/Program.cs:line 33                                                            at CasCap.Program.<Main>(String[] args)    

Note: It is not only one place as I try to use source code before that time. Did you use the latest API Call? A lot of standard Releases "read" too little values and other parts. For sample, I can see on azure 12 variables but ReleaseDefinition class return only 4.

**Comment by f2calv** [comment]
Please update to 2.0.1 and let me know if still a problem.

**Comment by daj102** [comment]
I have just installed 2.0.1 and I'm getting a similar issue; I do have Task Groups in my release pipelines and I'm getting this error when I run the tool:

`Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at CasCap.Utilities.YamlPipelineGenerator.GenSteps(Template template, Dictionary`2 inputs) in /_/src/CasCap.Apis.AzureDevOps/Utilities/YamlPipelineGenerator.cs:line 390
   at CasCap.Utilities.YamlPipelineGenerator.GetSteps(Template template, IDictionary`2 inputs) in /_/src/CasCap.Apis.AzureDevOps/Utilities/YamlPipelineGenerator.cs:line 386
`

That line refers to task group values:

`        var filename = $"{template.taskGroup.Name.Sanitize()}-v{template.taskGroup.Version.Major}.yml";
`

and all my task group names have spaces in ... they do have versions similar to "1.*" so it could be that too.

**Comment by daj102** [comment]
Oddly, putting in the `--inline` switch allows it to work, but it doesn't put the task groups inline in the pipelines - it still generates the task groups in separate files...

**Comment by f2calv** [comment]
I have no errors in my own integration tests (including with task groups) so I can only suggest that you debug this issue for yourself;

1. Clone the repo and open in latest Visual Studio.
2. Set *CasCap.DevOpsYamlizrCli* project as the start-up project.
3. Edit the [launchSettings.json](https://github.com/f2calv/yamlizr/blob/main/src/CasCap.DevOpsYamlizrCli/Properties/launchSettings.json) file with your own details;
```json
{
  "profiles": {
    "yamlizr": {
      "commandName": "Project",
      "commandLineArgs": "generate -pat 1111111122222222233333334444444444555555 -org https://dev.azure.com/some_org -proj my_proj -out c:/temp/myoutputfolder"
    }
  }
}
```
4. Hit Play (in Debug mode) and please create a PR and/or post to this thread when you find the issue.

**Comment by flcdrg** [comment]
Also getting this error

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.0:00 / 00:00:00
   at CasCap.Utilities.YamlPipelineGenerator.GenSteps(Template template, Dictionary`2 inputs) in /_/src/CasCap.Apis.AzureDevOps/Utilities/YamlPipelineGenerator.cs:line 390
```

One thing that is a possible culprit - the pipeline references an extension that has been removed

**Comment by glima** [comment]
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.                               00:00:00 / 00:00:00
   at CasCap.Utilities.YamlPipelineGenerator.GenSteps(Template template, Dictionary`2 inputs) in /_/src/CasCap.Api.AzureDevOps/Utilities/YamlPipelineGenerator.cs:line 391
   at CasCap.Utilities.YamlPipelineGenerator.GetSteps(Template template, IDictionary`2 inputs) in /_/src/CasCap.Api.AzureDevOps/Utilities/YamlPipelineGenerator.cs:line 387
   at CasCap.Utilities.YamlPipelineGenerator.GenSteps(Guid Id, String displayName, String semver, IDictionary`2 inputs, IDictionary`2 env, String condition, Boolean continueOnError, Int32 timeoutInMinutes, Dictionary`2 parameters) in /_/src/CasCap.Api.AzureDevOps/Utilities/YamlPipelineGenerator.cs:line 294
   at CasCap.Utilities.YamlPipelineGenerator.GenSteps(BuildDefinitionStep task) in /_/src/CasCap.Api.AzureDevOps/Utilities/YamlPipelineGenerator.cs:line 266
   at CasCap.Utilities.YamlPipelineGenerator.GenBuildStage() in /_/src/CasCap.Api.AzureDevOps/Utilities/YamlPipelineGenerator.cs:line 111
   at CasCap.Utilities.YamlPipelineGenerator.GenPipeline() in /_/src/CasCap.Api.AzureDevOps/Utilities/YamlPipelineGenerator.cs:line 68
   at CasCap.Commands.GenerateCommand.<>c__DisplayClass34_4.<OnExecuteAsync>g__ProcessDefinition|16(BuildDefinition buildDefinition) in /_/src/CasCap.DevOpsYamlizrCli/Commands/GenerateCommand.cs:line 245
   at CasCap.Commands.GenerateCommand.OnExecuteAsync() in /_/src/CasCap.DevOpsYamlizrCli/Commands/GenerateCommand.cs:line 227
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
15.83% YamlPipelineGenerator processed 139 of 878 build definition(s).                                                                  00:00:03 / 00:00:00
~ took 17s ─────────────▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

is what I get here :( Last version.
