### ISSUE TITLE
Error running export

### ISSUE THREAD

**Issue by scottlezberg** [f2calv/yamlizr#212]
I am trying to export and getting this error.  We use Azure DevOps Server 2022 (on-premise). - Any ideas on how to fix?

AzureDevOps/Utilities/YamlPipelineGenerator.cs:line 112
   at CasCap.Utilities.YamlPipelineGenerator.GenPipeline() in /_/src/CasCap.Apis.AzureDevOps/Utilities/YamlPipelineGenerator.cs:line 67
   at CasCap.Commands.GenerateCommand.<>c__DisplayClass31_4.<OnExecuteAsync>g__ProcessDefinition|16(BuildDefinition buildDefinition) in /_/src/CasCap.DevOpsYamlizrCli/Commands/GenerateCommand.cs:line 241
   at CasCap.Commands.GenerateCommand.OnExecuteAsync() in /_/src/CasCap.DevOpsYamlizrCli/Commands/GenerateCommand.cs:line 223
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at CasCap.Program.Main(String[] args) in /_/src/CasCap.DevOpsYamlizrCli/Program.cs:line 33
   at CasCap.Program.<Main>(String[] args)

**Comment by f2calv** [comment]
I can only suggest;
1. clone the repo & open in Visual Studio
2. add the required configuration parameters to https://github.com/f2calv/yamlizr/blob/main/src/CasCap.DevOpsYamlizrCli/Properties/launchSettings.json
3. execute DevOpsYamlizrCli application in Debug mode, and debug
4. create a PR if possible!
