### ISSUE TITLE
Exception while retrieving extensions

### ISSUE THREAD

**Issue by lzandman** [f2calv/yamlizr#235]
I'm getting a `System.ArgumentException` while retrieving all extensions. It happens on [line 132 in GenerateCommand.cs](https://github.com/f2calv/yamlizr/blob/5f54b9d8f7987fc35230f1055db35f2f07d4f401/src/CasCap.DevOpsYamlizrCli/Commands/GenerateCommand.cs#L132C13-L132C75).

It appears it tries to add an item that already exists. Shocker: our ADO instance's JSON response of the `distributedtasks/tasks` endpoint contains a task that has two `inputs` objects that have identical values for their `name` property. This seems like a bug, because the `task.json` for that particular task only contains one of the listed inputs. I know this, because it is one of our own internally developed extensions/tasks.

So, for now I think this is a bug in the ADO `distributedtasks/tasks` endpoint that's called in the [GetAllExtensions()](https://github.com/f2calv/yamlizr/blob/5f54b9d8f7987fc35230f1055db35f2f07d4f401/src/CasCap.Apis.AzureDevOps/Services/ApiService.cs#L25) `ApiService` method. What's weird is that this endpoint does not seem to be documented by Microsoft! So maybe it's an internal/undocumented API that you aren't supposed to call? Which might also explain why it is buggy.

Exception details:
```
System.ArgumentException
  HResult=0x80070057
  Message=An item with the same key has already been added. Key: ResourceGroupName
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException[T](T key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at CasCap.Commands.GenerateCommand.<OnExecuteAsync>d__31.MoveNext() in C:\Git\yamlizr\src\CasCap.DevOpsYamlizrCli\Commands\GenerateCommand.cs:line 132
```

**Comment by lzandman** [comment]
I will close this issue, as it seems it's a problem on our side. Somehow that particular DevOps extension/task got corrupted.
